# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :fail do
    begin
	foo()
    rescue => e
	raise e
    end
  end
  
  desc "Generate build"
  lane :build do
    sh("echo \"::group::My title\"")
    echo "Inside group"
    sh("echo \"::endgroup::\"")


    build_app(
  	scheme: "Playground",
	configuration: "Debug",
	export_method: "development"
    )	
  end

  lane :test do 
    puts "::group::Tests"
    puts "Inside group"
    puts "::endgroup::"

    run_tests(
      testplan: "Playground",
      scheme: "Playground",
      configuration: "Debug",
      sdk:"iphonesimulator",
      derived_data_path: "DerivedData",
      result_bundle: true,
      output_directory: "artifacts/",
      output_types: "junit"
    )  
  end  

	def foo()

	run_tests(
      testplan: "Playground",
      scheme: "Playground",
      configuration: "Debug",
      sdk:"iphonesimulator",
      derived_data_path: "DerivedData",
      result_bundle: true,
      output_directory: "artifacts/",
      output_types: "junit",
      fail_build: false
    )  
	end
end
