# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Generate build"
  lane :build do
    build_app(
  	scheme: "Playground",
	configuration: "Debug",
	export_method: "development"
    )	
  end

  lane :test do 
    run_tests(
      scheme: "Playground",
      configuration: "Debug",
      sdk:"iphonesimulator",
      derived_data_path: "DerivedData",
      result_bundle: true,
      output_directory: "artifacts/",
      output_types: "junit"
    )  
  end  
end
