name: Log Secret Keys Matching Value "Foo"

on:
  workflow_dispatch: # Trigger manually via the GitHub Actions UI

jobs:
  log-matching-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Find and log secret keys where the value is "Foo"
        run: |
          echo "Checking for secret keys with value 'Foo':"
          for secret_name in $(echo ${{ toJson(secrets) }} | jq -r 'keys[]'); do
            secret_value="${{ secrets[secret_name] }}"
            echo "::add-mask::$secret_value" # Mask the secret value
            if [[ "$secret_value" == "Foo" ]]; then
              echo "Matching secret key: $secret_name"
            fi
          done
