name: Log Secret Keys Matching Value "Foo"

on:
  workflow_dispatch: # Trigger manually via the GitHub Actions UI

jobs:
  log-matching-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Define secret names
        run: echo "SECRET_NAMES='HIDE_INFO_1 SLACK_WEBHOOK_URL FOO_SECRET'" >> $GITHUB_ENV

      - name: Check secrets
        run: |
          echo "Checking for secret keys with value 'Foo':"
          for secret_name in $SECRET_NAMES; do
            secret_value=$(eval echo "\${{ secrets.$secret_name }}")
            echo "::add-mask::$secret_value" # Mask the secret value
            if [[ "$secret_value" == "Foo" ]]; then
              echo "Matching secret key: $secret_name"
            fi
          done
