name: Log Secret Keys Matching Value "Foo"

on:
  workflow_dispatch: # Trigger manually via the GitHub Actions UI

jobs:
  log-matching-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check secrets manually
        env:
          MY_SECRET_1: ${{ secrets.FOO_SECRET }}
          MY_SECRET_2: ${{ secrets.HIDE_INFO }}
        run: |
          echo "Checking for secret keys with value 'Foo':"
          for secret_name in MY_SECRET_1 MY_SECRET_2; do
            secret_value=$(eval echo "\$$secret_name")
            echo "::add-mask::$secret_value" # Mask the secret value
            if [[ "$secret_value" == "Foo" ]]; then
              echo "Matching secret key: $secret_name"
            fi
          done
