# This is a basic workflow to help you get started with Actions

name: Fail


on:
  workflow_dispatch:

jobs:
  fail:
    runs-on: macos-14  
    
    steps:
      - uses: actions/checkout@v3
      - name: bundler install
        run: bundle install
      - name: run fail lane
        run: |
          bundle exec fastlane fail
