name: Skip trigger

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUN_CRITICAL_FLOWS: ${{ inputs.branch != 'release/cycle-3.120' }}
jobs:
  run-tests:
    name: Run tests
    steps:
      - name: Install 1Password
        if: ${{ env.RUN_CRITICAL_FLOWS }}
        uses: 1password/install-cli-action@v1
