name: Test worflow develop PR

on: 
  workflow_dispatch:
  pull_request:
    types: [ opened, synchronize, edited, ready_for_review ]
    branches: [ 'main' ]

permissions: 
  checks: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: echo
        run: |
          echo "I run all the time"
